name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
    paths:
      - 'client/**' # Only trigger on changes in the client directory
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install and Build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: |
          cd client
          npm ci
          npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEEPCARDS_432519 }}
          channelId: live
          projectId: deepcards-432519
          entryPoint: './client' # Specify the client directory as the entry point
